 -- Country Codes
 
insert into country_codes values("AF", "Afghanistan");
insert into country_codes values("AL", "Albania");
insert into country_codes values("DZ", "Algeria");
insert into country_codes values("AS", "American Samoa");
insert into country_codes values("AD", "Andorra");
insert into country_codes values("AO", "Angola");
insert into country_codes values("AI", "Anguilla");
insert into country_codes values("AQ", "Antarctica");
insert into country_codes values("AG", "Antigua and Barbuda");
insert into country_codes values("AR", "Argentina");
insert into country_codes values("AM", "Armenia");
insert into country_codes values("AW", "Aruba");
insert into country_codes values("AU", "Australia");
insert into country_codes values("AT", "Austria");
insert into country_codes values("AZ", "Azerbaijan");
insert into country_codes values("BS", "Bahamas");
insert into country_codes values("BH", "Bahrain");
insert into country_codes values("BD", "Bangladesh");
insert into country_codes values("BB", "Barbados");
insert into country_codes values("BY", "Belarus");
insert into country_codes values("BE", "Belgium");
insert into country_codes values("BZ", "Belize");
insert into country_codes values("BJ", "Benin");
insert into country_codes values("BM", "Bermuda");
insert into country_codes values("BT", "Bhutan");
insert into country_codes values("BO", "Bolivia");
insert into country_codes values("BQ", "Bonaire");
insert into country_codes values("BA", "Bosnia and Herzegovina");
insert into country_codes values("BW", "Botswana");
insert into country_codes values("BV", "Bouvet Island");
insert into country_codes values("BR", "Brazil");
insert into country_codes values("IO", "British Indian Ocean Territory");
insert into country_codes values("BN", "Brunei Darussalam");
insert into country_codes values("BG", "Bulgaria");
insert into country_codes values("BF", "Burkina Faso");
insert into country_codes values("BI", "Burundi");
insert into country_codes values("KH", "Cambodia");
insert into country_codes values("CM", "Cameroon");
insert into country_codes values("CA", "Canada");
insert into country_codes values("CV", "Cape Verde");
insert into country_codes values("KY", "Cayman Islands");
insert into country_codes values("CF", "Central African Republic");
insert into country_codes values("TD", "Chad");
insert into country_codes values("CL", "Chile");
insert into country_codes values("CN", "China");
insert into country_codes values("CX", "Christmas Island");
insert into country_codes values("CC", "Cocos (Keeling) Islands");
insert into country_codes values("CO", "Colombia");
insert into country_codes values("KM", "Comoros");
insert into country_codes values("CG", "Congo");
insert into country_codes values("CD", "Democratic Republic of the Congo");
insert into country_codes values("CK", "Cook Islands");
insert into country_codes values("CR", "Costa Rica");
insert into country_codes values("HR", "Croatia");
insert into country_codes values("CU", "Cuba");
insert into country_codes values("CW", "Curacao");
insert into country_codes values("CY", "Cyprus");
insert into country_codes values("CZ", "Czech Republic");
insert into country_codes values("CI", "Cote d'Ivoire");
insert into country_codes values("DK", "Denmark");
insert into country_codes values("DJ", "Djibouti");
insert into country_codes values("DM", "Dominica");
insert into country_codes values("DO", "Dominican Republic");
insert into country_codes values("EC", "Ecuador");
insert into country_codes values("EG", "Egypt");
insert into country_codes values("SV", "El Salvador");
insert into country_codes values("GQ", "Equatorial Guinea");
insert into country_codes values("ER", "Eritrea");
insert into country_codes values("EE", "Estonia");
insert into country_codes values("ET", "Ethiopia");
insert into country_codes values("FK", "Falkland Islands (Malvinas)");
insert into country_codes values("FO", "Faroe Islands");
insert into country_codes values("FJ", "Fiji");
insert into country_codes values("FI", "Finland");
insert into country_codes values("FR", "France");
insert into country_codes values("GF", "French Guiana");
insert into country_codes values("PF", "French Polynesia");
insert into country_codes values("TF", "French Southern Territories");
insert into country_codes values("GA", "Gabon");
insert into country_codes values("GM", "Gambia");
insert into country_codes values("GE", "Georgia");
insert into country_codes values("DE", "Germany");
insert into country_codes values("GH", "Ghana");
insert into country_codes values("GI", "Gibraltar");
insert into country_codes values("GR", "Greece");
insert into country_codes values("GL", "Greenland");
insert into country_codes values("GD", "Grenada");
insert into country_codes values("GP", "Guadeloupe");
insert into country_codes values("GU", "Guam");
insert into country_codes values("GT", "Guatemala");
insert into country_codes values("GG", "Guernsey");
insert into country_codes values("GN", "Guinea");
insert into country_codes values("GW", "Guinea-Bissau");
insert into country_codes values("GY", "Guyana");
insert into country_codes values("HT", "Haiti");
insert into country_codes values("HM", "Heard Island and McDonald Islands");
insert into country_codes values("VA", "Holy See (Vatican City State)");
insert into country_codes values("HN", "Honduras");
insert into country_codes values("HK", "Hong Kong");
insert into country_codes values("HU", "Hungary");
insert into country_codes values("IS", "Iceland");
insert into country_codes values("IN", "India");
insert into country_codes values("ID", "Indonesia");
insert into country_codes values("IR", "Iran Islamic Republic of");
insert into country_codes values("IQ", "Iraq");
insert into country_codes values("IE", "Ireland");
insert into country_codes values("IM", "Isle of Man");
insert into country_codes values("IL", "Israel");
insert into country_codes values("IT", "Italy");
insert into country_codes values("JM", "Jamaica");
insert into country_codes values("JP", "Japan");
insert into country_codes values("JE", "Jersey");
insert into country_codes values("JO", "Jordan");
insert into country_codes values("KZ", "Kazakhstan");
insert into country_codes values("KE", "Kenya");
insert into country_codes values("KI", "Kiribati");
insert into country_codes values("KP", "Korea Democratic People's Republic of");
insert into country_codes values("KR", "Korea Republic of");
insert into country_codes values("KW", "Kuwait");
insert into country_codes values("KG", "Kyrgyzstan");
insert into country_codes values("LA", "Lao People's Democratic Republic");
insert into country_codes values("LV", "Latvia");
insert into country_codes values("LB", "Lebanon");
insert into country_codes values("LS", "Lesotho");
insert into country_codes values("LR", "Liberia");
insert into country_codes values("LY", "Libya");
insert into country_codes values("LI", "Liechtenstein");
insert into country_codes values("LT", "Lithuania");
insert into country_codes values("LU", "Luxembourg");
insert into country_codes values("MO", "Macao");
insert into country_codes values("MK", "Macedonia the Former Yugoslav Republic of");
insert into country_codes values("MG", "Madagascar");
insert into country_codes values("MW", "Malawi");
insert into country_codes values("MY", "Malaysia");
insert into country_codes values("MV", "Maldives");
insert into country_codes values("ML", "Mali");
insert into country_codes values("MT", "Malta");
insert into country_codes values("MH", "Marshall Islands");
insert into country_codes values("MQ", "Martinique");
insert into country_codes values("MR", "Mauritania");
insert into country_codes values("MU", "Mauritius");
insert into country_codes values("YT", "Mayotte");
insert into country_codes values("MX", "Mexico");
insert into country_codes values("F", "Micronesia Federated States of");
insert into country_codes values("M", "Moldova Republic of");
insert into country_codes values("MC", "Monaco");
insert into country_codes values("MN", "Mongolia");
insert into country_codes values("ME", "Montenegro");
insert into country_codes values("MS", "Montserrat");
insert into country_codes values("MA", "Morocco");
insert into country_codes values("MZ", "Mozambique");
insert into country_codes values("MM", "Myanmar");
insert into country_codes values("NA", "Namibia");
insert into country_codes values("NR", "Nauru");
insert into country_codes values("NP", "Nepal");
insert into country_codes values("NL", "Netherlands");
insert into country_codes values("NC", "New Caledonia");
insert into country_codes values("NZ", "New Zealand");
insert into country_codes values("NI", "Nicaragua");
insert into country_codes values("NE", "Niger");
insert into country_codes values("NG", "Nigeria");
insert into country_codes values("NU", "Niue");
insert into country_codes values("NF", "Norfolk Island");
insert into country_codes values("MP", "Northern Mariana Islands");
insert into country_codes values("NO", "Norway");
insert into country_codes values("OM", "Oman");
insert into country_codes values("PK", "Pakistan");
insert into country_codes values("PW", "Palau");
insert into country_codes values("P", "Palestine State of");
insert into country_codes values("PA", "Panama");
insert into country_codes values("PG", "Papua New Guinea");
insert into country_codes values("PY", "Paraguay");
insert into country_codes values("PE", "Peru");
insert into country_codes values("PH", "Philippines");
insert into country_codes values("PN", "Pitcairn");
insert into country_codes values("PL", "Poland");
insert into country_codes values("PT", "Portugal");
insert into country_codes values("PR", "Puerto Rico");
insert into country_codes values("QA", "Qatar");
insert into country_codes values("RO", "Romania");
insert into country_codes values("RU", "Russian Federation");
insert into country_codes values("RW", "Rwanda");
insert into country_codes values("RE", "Reunion");
insert into country_codes values("BL", "Saint Barthelemy");
insert into country_codes values("SH", "Saint Helena");
insert into country_codes values("KN", "Saint Kitts and Nevis");
insert into country_codes values("LC", "Saint Lucia");
insert into country_codes values("MF", "Saint Martin (French part)");
insert into country_codes values("PM", "Saint Pierre and Miquelon");
insert into country_codes values("VC", "Saint Vincent and the Grenadines");
insert into country_codes values("WS", "Samoa");
insert into country_codes values("SM", "San Marino");
insert into country_codes values("ST", "Sao Tome and Principe");
insert into country_codes values("SA", "Saudi Arabia");
insert into country_codes values("SN", "Senegal");
insert into country_codes values("RS", "Serbia");
insert into country_codes values("SC", "Seychelles");
insert into country_codes values("SL", "Sierra Leone");
insert into country_codes values("SG", "Singapore");
insert into country_codes values("SX", "Sint Maarten (Dutch part)");
insert into country_codes values("SK", "Slovakia");
insert into country_codes values("SI", "Slovenia");
insert into country_codes values("SB", "Solomon Islands");
insert into country_codes values("SO", "Somalia");
insert into country_codes values("ZA", "South Africa");
insert into country_codes values("GS", "South Georgia and the South Sandwich Islands");
insert into country_codes values("SS", "South Sudan");
insert into country_codes values("ES", "Spain");
insert into country_codes values("LK", "Sri Lanka");
insert into country_codes values("SD", "Sudan");
insert into country_codes values("SR", "Suriname");
insert into country_codes values("SJ", "Svalbard and Jan Mayen");
insert into country_codes values("SZ", "Swaziland");
insert into country_codes values("SE", "Sweden");
insert into country_codes values("CH", "Switzerland");
insert into country_codes values("SY", "Syrian Arab Republic");
insert into country_codes values("TW", "Taiwan");
insert into country_codes values("TJ", "Tajikistan");
insert into country_codes values("TZ", "United Republic of Tanzania");
insert into country_codes values("TH", "Thailand");
insert into country_codes values("TL", "Timor-Leste");
insert into country_codes values("TG", "Togo");
insert into country_codes values("TK", "Tokelau");
insert into country_codes values("TO", "Tonga");
insert into country_codes values("TT", "Trinidad and Tobago");
insert into country_codes values("TN", "Tunisia");
insert into country_codes values("TR", "Turkey");
insert into country_codes values("TM", "Turkmenistan");
insert into country_codes values("TC", "Turks and Caicos Islands");
insert into country_codes values("TV", "Tuvalu");
insert into country_codes values("UG", "Uganda");
insert into country_codes values("UA", "Ukraine");
insert into country_codes values("AE", "United Arab Emirates");
insert into country_codes values("GB", "United Kingdom");
insert into country_codes values("US", "United States");
insert into country_codes values("UM", "United States Minor Outlying Islands");
insert into country_codes values("UY", "Uruguay");
insert into country_codes values("UZ", "Uzbekistan");
insert into country_codes values("VU", "Vanuatu");
insert into country_codes values("VE", "Venezuela");
insert into country_codes values("VN", "Viet Nam");
insert into country_codes values("VG", "British Virgin Islands");
insert into country_codes values("VI", "US Virgin Islands");
insert into country_codes values("WF", "Wallis and Futuna");
insert into country_codes values("EH", "Western Sahara");
insert into country_codes values("YE", "Yemen");
insert into country_codes values("ZM", "Zambia");
insert into country_codes values("ZW", "Zimbabwe");

-- Customers

-- Customer Cards

-- Payment Types

insert into payment_types values(default, "Cash");
insert into payment_types values(default, "Credit");

-- Product Types

insert into product_types values(default, "Beverage");
insert into product_types values(default, "Pastry");

-- Products

-- Sales Orders

-- Sales Order Items
